name: Workload Identity Federation Test
on: [pull_request]

permissions:
  id-token: write
  contents: 'read'

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
  
      # actions/checkout MUST come before auth
      - uses: 'actions/checkout@v3'

      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v0.3.1"
        with:
          workload_identity_provider: "projects/1017300651546/locations/global/workloadIdentityPools/domen-personal-pool/providers/github"
          service_account: " domen-workload-identity-federa@domen-telegram-bot.iam.gserviceaccount.com"

      - id: "gcloud"
        name: "gcloud"
        run: |-
          gcloud services list --project domen-telegram-bot